name: "AI Code Review Action Version 3"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  REVIEW_MAX_COMMENTS:
    description: "Maximum number of comments to include in a review (per diff)."
    required: false
    default: "5"
  REVIEW_PROJECT_CONTEXT:
    description: "Project context to include in a review. E.g. Typescript with NestJS + TypeORM"
    required: false
    default: ""
  APPROVE_REVIEWS:
    description: "Whether to approve PR reviews or just comment"
    required: false
    default: "false"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
  BEDROCK_MODEL_ID:
    description: "Model ID"
    required: false
    # Use specific prefix sagemaker.<api url> to specify the model hosted in AWS SageMaker
    # default: "anthropic.claude-3-5-sonnet-20240620-v1:0"
    default: "anthropic.claude-3-sonnet-20240229-v1:0"
  AWS_REGION:
    description: "AWS region"
    required: false
    default: "us-east-1"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
