# Code Review Version 3 - Claude3
#
# The action used in this workflow refers to the project found at https://github.com/freeedcom/ai-codereviewer.
#

name: Code Review Version 3 - Claude3

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  issues: write
  pull-requests: write
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  code_review_v3_claude:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev # checkout dev branch to use the latest action
        # Number of commits to fetch. 0 indicates all history for all branches and tags.
        # Default: 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      # Install dependencies in .github/actions/aws-genai-cicd to ensure your custom action takes effect.
      - name: Install dependencies
        run: npm install
        shell: bash
        working-directory: .github/actions/ai-codereviewer

      # Generate dist/index.js in .github/actions/aws-genai-cicd by executing `npm run build`.
      - name: Build project
        run: npm run build
        shell: bash
        working-directory: .github/actions/ai-codereviewer

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: gha-session
          role-duration-seconds: 3600

      - name: Get AWS credentials (Optional Step)
        run: aws sts get-caller-identity

      - name: AI Code Reviewer
        uses: ./.github/actions/ai-codereviewer
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
          # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
